version: "3.8"

services:
  postgres-db:
    image: postgres:13.6
    restart: always
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - postgres-db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    environment:
      ETHEREUM_JSONRPC_VARIANT: "ganache"
      ETHEREUM_JSONRPC_HTTP_URL: http://ganache-cli:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://ganache-cli:8545/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      ECTO_USE_SSL: "false"
      COIN: ""
      CACHE_EXCHANGE_RATES_PERIOD: ""
      DISABLE_READ_API: "false"
      API_PATH: "/"
      NETWORK_PATH: "/"
      DISABLE_WEBAPP: "false"
      DISABLE_WRITE_API: "false"
      CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
      WOBSERVER_ENABLED: "false"
      ADMIN_PANEL_ENABLED: ""
      SUBNETWORK: "carelo chain"
      SECRET_KEY_BASE: KMtNJ/pHZfrpCU8lVJk4XhpkQUbZOzXCYpj2Ri1ERSLB/zn64RaAA6/mzPcySYtX
    restart: always
    container_name: "blockscout"
    links:
      - postgres-db:postgres
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./envs/common-blockscout.env
    ports:
      - 4000:4000
networks:
  default:
    labels:
      org.fiware: "blockscout"
    driver: bridge
