---
components:
  schemas:
    Activity:
      $ref: "https://raw.githubusercontent.com/jo-al-ra/ca-re-lo/main/data-models/Activity/model.yaml#/Activity"

    Asset:
      $ref: "https://raw.githubusercontent.com/jo-al-ra/ca-re-lo/12-asset-templates/data-models/Asset/model.yaml#/Asset"
    Claim:
      $ref: "https://raw.githubusercontent.com/jo-al-ra/ca-re-lo/main/data-models/Claim/model.yaml#/Claim"

    Actor:
      allOf:
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common"
      properties:
        description:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description"
        name:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name"
        publicKey:
          type: string

    Safeguard:
      $ref: "https://raw.githubusercontent.com/jo-al-ra/ca-re-lo/main/data-models/Safeguard/model.yaml#/Safeguard"

    # This is a defintion of a person.
    Person:
      allOf:
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/ngsi-ld.yaml#/Common"
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/schema.org.yaml#/Person"
    Gender:
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/schema.org.yaml#/GenderType"
info:
  description: "Base Model Definitions from Smart Data Models"
  title: Baseline Models
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          description: OK
          content:
            application/ld+json:
              schema:
                type: object
