---
components:
  schemas:
    # This is the base definition of a DLTtxReceipt
    DLTtxReceipt:
      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.DistributedLedgerTech/master/DLTtxReceipt/model.yaml#/DLTtxReceipt"

    Activity:
      allOf:
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common"
      properties:
        description:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description"
        usedTools:
          type: array
          items:
            $ref: "#/components/schemas/Asset"
        ownedBy:
          type: array
          items:
            $ref: "#/components/schemas/Actor"
        produces:
          type: array
          items:
            $ref: "#/components/schemas/Asset"
        consumes:
          type: array
          items:
            $ref: "#/components/schemas/Asset"

    Asset:
      allOf:
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common"
      properties:
        description:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description"
        name:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name"
        ownedBy:
          $ref: "#/components/schemas/Actor"
        hasCertificates:
          type: array
          items:
            $ref: "#/components/schemas/Certificate"
        producedVia:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: "Property. Identifier format of any NGSI entity"
              format: uri
              type: string
          description: "Entity, that represents the production of this asset (e.g. manufacturing or chemical activity)"
          x-ngsi:
            type: Relationship
        consumedVia:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: "Property. Identifier format of any NGSI entity"
              format: uri
              type: string
          description: "Entity, that represents the consumption of this asset (e.g. manufacturing or chemical activity)"
          x-ngsi:
            type: Relationship
        usedFor:
          type: array
          items:
            anyOf:
              - description: "Property. Identifier format of any NGSI entity"
                maxLength: 256
                minLength: 1
                pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
                type: string
              - description: "Property. Identifier format of any NGSI entity"
                format: uri
                type: string
          description: "Entities, that this asset was used for (e.g. as a tool for an activity) without significant degradation of the asset itself."
          x-ngsi:
            type: Relationship

    Certificate:
      allOf:
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common"
      properties:
        description:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description"
        name:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name"
        solidCarbonContent:
          type: string
        carbonFootprint:
          type: string
        isWastematerial:
          type: boolean
        issuedFor:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: "Property. Identifier format of any NGSI entity"
              format: uri
              type: string
          description: "Entity, that this certificate is about"
          x-ngsi:
            type: Relationship
        issuedBy:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: "Property. Identifier format of any NGSI entity"
              format: uri
              type: string
          description: "Entity, that issued the certificate"
          x-ngsi:
            type: Relationship

    Actor:
      allOf:
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common"
      properties:
        description:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description"
        name:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name"
        publicKey:
          type: string

    Safeguard:
      allOf:
        - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common"
      properties:
        description:
          allOf:
            - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description"
        category:
          type: string
          enum:
            - verification
            - validation
            - appeal
        seeAlso:
          type: string
        ownedBy:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: "Property. Identifier format of any NGSI entity"
              format: uri
              type: string
          description: "Entity, that controls the safeguard"
          x-ngsi:
            type: Relationship
        references:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: "Property. Identifier format of any NGSI entity"
              format: uri
              type: string
          description: "Entity the Safeguard references"
          x-ngsi:
            type: Relationship

    # This is a defintion of a person.
    Person:
      allOf:
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/ngsi-ld.yaml#/Common"
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/schema.org.yaml#/Person"
    Gender:
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/schema.org.yaml#/GenderType"
info:
  description: "Base Model Definitions from Smart Data Models"
  title: Baseline Models
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          description: OK
          content:
            application/ld+json:
              schema:
                type: object
